[package]
name = "opsml-server"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

authors = [
  "Steven Forrester <sjforrester32@gmail.com>"
]

license = "MIT"
description = "Core rust library for the opsml project"

[dependencies]
serde = { version = "1.*", features = ["derive"] }
tokio = { version = "1.*", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1.*"
tower-http = { version = "0.5.0", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["json", "time"]}
axum = "0.7.7"
opsml-storage = { workspace = true, features = ["google_storage"] }


[dev-dependencies]
mockall = "0.*"
mockito = "1.*"
rand = "0.8.5"

[profile.release]
lto = "fat"
codegen-units = 1
strip = true
