[package]
name = "opsml-core"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

authors = [
  "Steven Forrester <sjforrester32@gmail.com>"
]

license = "MIT"
description = "Core rust library for the opsml project"

[dependencies]
pyo3 = { workspace = true }
serde = { version = "1.0.163", features = ["derive"] }
native-tls = { version = "0.2", features = ["vendored"] }
reqwest = { version = "0.11.22", features = ["blocking", "json", "stream", "native-tls"], default-features = false }
tokio = { version = "1.34.0"}


[dev-dependencies]
mockito = "1.4.0"


[profile.release]
lto = "fat"
codegen-units = 1
strip = true
