[package]
name = "opsml-types"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[lib]
doctest = false


[dependencies]
opsml-utils = { workspace = true }
pyo3 = { workspace = true }
serde = { workspace = true }
